#Generate the client id and secret from Azure Active Directory
app_id: "#####################################"
app_secret: "####################################"
#Add this as redirect uri in Azure Active Directory
redirect: "https://localhost:8000/aad-callback/"
scopes: "openid profile offline_access user.read"
authority: "https://login.microsoftonline.com"
authorize_endpoint: "/common/oauth2/v2.0/authorize"
token_endpoint: "/common/oauth2/v2.0/token"