app_id: "25eeed49-a30e-44cb-b3d5-f37e976b2122"
app_secret: "j4quMPhi0m7~3I.L83~K5O1n.rlxE17qyn"
redirect: "https://localhost:8000/aad-callback/"
scopes: "openid profile offline_access user.read "
authority: "https://login.microsoftonline.com"
authorize_endpoint: "/850aa78d-94e1-4bc6-9cf3-8c11b530701c/oauth2/v2.0/authorize"
token_endpoint: "/850aa78d-94e1-4bc6-9cf3-8c11b530701c/oauth2/v2.0/token"