# Generated by Django 3.1.7 on 2021-06-24 16:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoChatRoom',
            fields=[
                ('room_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('active_members', models.JSONField(default=list)),
                ('members', models.ManyToManyField(related_name='video_chat_rooms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
