# Generated by Django 3.1.7 on 2021-06-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videochatroom',
            name='active_members',
            field=models.JSONField(default=list),
        ),
    ]
