# Generated by Django 3.1.7 on 2021-07-09 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invited',
            field=models.ManyToManyField(related_name='invited_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
