# Generated by Django 3.1.7 on 2021-07-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_team_invited'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='unseen_notif',
            field=models.BooleanField(default=False),
        ),
    ]
