# Generated by Django 3.1.7 on 2021-07-09 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_account_unseen_notif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='unseen_notif',
            new_name='new_notif',
        ),
    ]
