# Generated by Django 3.1.7 on 2021-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210709_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_personal',
            field=models.BooleanField(default=False),
        ),
    ]
